### ISSUE TITLE
Переделать на rxjs

### ISSUE THREAD

**Issue by Zaklinatel** [assisken/emoji-list#4]
https://github.com/assisken/emoji-list/blob/e6c092aeaa1217c0bbfa37871f6a51d09849533a/src/app/emoji.service.ts#L16-L23

Безусловно, async/await - это круто и модно, но Angular работает в основном с библиотекой rxjs, которая, в общем-то, пропагандирует особое мышление и подход к написанию и организации асинхронного кода. Не зря все асинхронные действия в Angular возвращают Observable.

Сделай через обозревателей. Все асинхронные методы должны возвращать Observable (и быть синхронными).

**Comment by assisken** [comment]
Машина времени мне подсказала, что проект, носящий сугубо исследовательские цели, заброшен. Закрою-ка я issue в таком случае...
